# load in NumPy (remember to pip install numpy first)

In [6]:
import numpy as np

# The Basics

In [10]:
a = np.array([1,2,3])

In [12]:
print (a)

[1 2 3]


In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print (b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
# Get Diamension of array
a.ndim

1

In [23]:
b.ndim

2

In [25]:
# Get Shape
a.shape

(3,)

In [27]:
b.shape

(2, 3)

In [ ]:
#Get Type

In [29]:
a.dtype

dtype('int64')

In [31]:
b.dtype

dtype('float64')

In [35]:
x= np.array([1,2,3], dtype = 'int16')

In [37]:
x.dtype

dtype('int16')

In [39]:
# Get Size
a.itemsize

8

In [41]:
x.itemsize

2

In [45]:
a.size

3

In [43]:
# Total Size
a.size * a.itemsize

24

In [47]:
a.nbytes

24

In [49]:
b.itemsize

8

In [51]:
b.size

6

In [53]:
b.nbytes

48

In [55]:
b.dtype

dtype('float64')

In [57]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [59]:
a.shape

(2, 7)

In [65]:
# To get an specific element [r, c]/[remember python starts from 0]
a[1,5]

13

In [67]:
a[-1,-2]

13

In [71]:
# Get an spacific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [73]:
# get an specific Column
a[ :, 2]

array([ 3, 10])

In [81]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [83]:
a[1, 2:13:1]

array([10, 11, 12, 13, 14])

In [85]:
# if you want to change any element in row/col
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [87]:
a[:,2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [91]:
a[:,2] = [1,2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3-D expample

In [95]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [99]:
# Get specific element (work outside in)
b[0,1,1]

4

In [101]:
b[1,1,1]

8

In [103]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [105]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [111]:
# replace elements here
b[:,1,:] = [[9,9],[8,8]]
print (b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [ ]:
# All 0s matrix

In [122]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [128]:
# All 1s matris
np.ones((2,3,3), dtype= 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [138]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [136]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [140]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [142]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [153]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.18631498, 0.27725075],
       [0.76971282, 0.7503129 ],
       [0.95798249, 0.05877943],
       [0.0881996 , 0.71338665]])

In [166]:
# Random Integer Value
np.random.randint(1,5, size=(3,3))

array([[2, 2, 1],
       [4, 2, 1],
       [4, 2, 4]])

In [174]:
# The Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [178]:
#r= Repeat array multiple times
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis = 0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [180]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis = 1)
print (r1)

[[1 1 1 2 2 2 3 3 3]]
